<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;

class UpdateStockBagRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'barcode_code' => 'nullable|string|max:100|unique:stock_bags,barcode_code,' . ($this->route('stock_bag') ?? $this->route('id')),
            'bag_weight' => 'sometimes|required|numeric|min:0.01',
            'unit_price' => 'nullable|numeric|min:0',
            'selling_price' => 'nullable|numeric|min:0',
            'status' => 'nullable|string|in:in_stock,dispatched,damaged,returned',
            'location_id' => 'nullable|string|max:100',
            'notes' => 'nullable|string',
        ];
    }

    /**
     * Configure the validator instance for Barcode Token verification.
     */
    public function withValidator(Validator $validator): void
    {
        $validator->after(function ($validator) {
            $barcodeCode = $this->input('barcode_code');
            if (empty($barcodeCode)) {
                return;
            }

            $currentStockBagId = $this->route('stock_bag') ?? $this->route('id');
            $currentStockBag = \App\Models\StockBag::find($currentStockBagId);

            // If updating to the same barcode already assigned to this bag, allow it
            if ($currentStockBag && $currentStockBag->barcode_code === $barcodeCode) {
                return;
            }

            $token = \App\Models\BarcodeToken::where('token_code', $barcodeCode)->first();

            if (!$token) {
                $validator->errors()->add('barcode_code', "The barcode '{$barcodeCode}' was not generated by the system.");
                return;
            }

            if ($token->status === 'used') {
                $validator->errors()->add('barcode_code', "The barcode '{$barcodeCode}' has already been used.");
            } elseif ($token->status === 'cancelled') {
                $validator->errors()->add('barcode_code', "The barcode '{$barcodeCode}' has been cancelled and cannot be used.");
            }
        });
    }

    /**
     * Handle failed validation and return a JSON error response.
     */
    protected function failedValidation(Validator $validator)
    {
        $errorMessages = $validator->errors();

        $fieldErrors = collect($errorMessages->getMessages())->map(function ($messages, $field) {
            return [
                'field' => $field,
                'messages' => $messages,
            ];
        })->values();

        $message = $fieldErrors->count() > 1
            ? 'There are multiple validation errors. Please review the form and correct the issues.'
            : 'There is an issue with the input for ' . $fieldErrors->first()['field'] . '.';

        throw new HttpResponseException(response()->json([
            'message' => $message,
            'errors' => $fieldErrors,
        ], 422));
    }
}
